/*
Package swaggerpetstoreopenapi30

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package tests

import (
    "github.com/apimatic/go-core-runtime/https"
    "swaggerpetstoreopenapi30"
    "swaggerpetstoreopenapi30/controllers"
)

var StoreController controllers.StoreController

func init() {
    config := swaggerpetstoreopenapi30.ConfigurationFactory(
        swaggerpetstoreopenapi30.WithHttpConfiguration(
            swaggerpetstoreopenapi30.HttpConfigurationFactory(
                https.WithTimeout(30),
            ),
        ),
    )
    
    client := swaggerpetstoreopenapi30.NewClient(config)
    
    StoreController = client.StoreController
}
