/*
Package swaggerpetstoreopenapi30

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package controllers

import (
    "github.com/apimatic/go-core-runtime/https"
    "net/http"
)

type callBuilderFactory interface {
	GetCallBuilder() https.CallBuilderFactory
}

type baseController struct {
	callBuilder    callBuilderFactory
	prepareRequest https.CallBuilderFactory
}

func NewBaseController(cb callBuilderFactory) *baseController {
	baseController := baseController{callBuilder: cb}
	baseController.prepareRequest = baseController.callBuilder.GetCallBuilder()
	return &baseController
}

func validateResponse(response http.Response) error {
	return nil
}
