/*
Package swaggerpetstoreopenapi30

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package models

// Order Status
type OrderStatusEnum string

const (
    OrderStatusEnum_PLACED    OrderStatusEnum = "placed"
    OrderStatusEnum_APPROVED  OrderStatusEnum = "approved"
    OrderStatusEnum_DELIVERED OrderStatusEnum = "delivered"
)

// pet status in the store
type PetStatusEnum string

const (
    PetStatusEnum_AVAILABLE PetStatusEnum = "available"
    PetStatusEnum_PENDING   PetStatusEnum = "pending"
    PetStatusEnum_SOLD      PetStatusEnum = "sold"
)

type StatusEnum string

const (
    StatusEnum_AVAILABLE StatusEnum = "available"
    StatusEnum_PENDING   StatusEnum = "pending"
    StatusEnum_SOLD      StatusEnum = "sold"
)
